default_platform(:android)
platform :android do
  desc "Deploy to Google Play Store"
  lane :deploy do |options|
    track = options[:track] || "internal"
    upload_to_play_store(
      track: track,
      aab: "../build/app/outputs/bundle/release/app-release.aab",
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true,
      release_status: "draft"
    )
  end
end
